# Generated by Django 4.1 on 2022-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do cliente')),
                ('cpf', models.FloatField(verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('ano', models.IntegerField(verbose_name='Ano de lancamento')),
                ('autor', models.CharField(max_length=250, verbose_name='Autor')),
            ],
        ),
    ]
