# Generated by Django 4.1 on 2022-08-09 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alugados'),
    ]

    operations = [
        migrations.AddField(
            model_name='alugados',
            name='data_do_aluguel',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
